### PR TITLE
SSB create players guide

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Lord-Haji** [comment]
It would be better if its a Command on the server rather a MarkDown on Github

**Comment by ghost** [comment]
#186 @Lord-Haji

**Comment by ghost** [comment]
@HoeenCoder merge this one first so I can edit the other pr and add it

**Comment by HoeenCoder** [comment]
Stella combine your PR's into one

**Comment by ghost** [comment]
Done

**Pull request closed without merging**
