### PR TITLE
SGSSB: Move touch ups

### PR DESCRIPTION
**Pull request by ghost**
Makes it so Mewtation can first raise its evasion THEN badly poison the target. Mainly to get rid of the immune fails as well as make Mewtation not as dead weight

### CODE REVIEW

**Comment by ghost** [comment]
changed some setup moves with the target normal to self to prevent failing during use while the opponent uses sub

**Comment by DeathlyPlays** [comment]
Is this tested

**Comment by RagiingAlways** [comment]
The self: { parts before noting the boosts of those moves can be remove with the edit of the target.

**Comment by ghost** [comment]
Everything works!

**Comment by DeathlyPlays** [comment]
You got some eslint issues @Gligar

**Pull request merged**
