### PR TITLE
Vouchers: Utilize name color on popups

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by HoeenCoder** [comment]
Vouchers are deperciated atm, dont bother.

**Comment by DeathlyPlays** [comment]
Deprecated?

**Comment by ghost** [comment]
Depreciated

**Comment by DeathlyPlays** [comment]
Wdym

**Comment by ghost** [comment]
Vouchers are basically NU

**Comment by ghost** [comment]
They aren’t used as much as we like to sadly :/

**Comment by DeathlyPlays** [comment]
ah

**Pull request closed without merging**
