### PR TITLE
Uno: Display Card Images

### PR DESCRIPTION
**Pull request by Lord-Haji**
TODO Checklist
- [x] Red
- [x] Green
- [x] Blue
- [x] Yellow
- [x] Black
- [x] ``/uno showcase`` - Crash FIx
- [x] Add credits
- [x] Fix Wild Cards
- [x] Add 0 value cards

New images origin http://imgur.com/gallery/YKb8m

### CODE REVIEW

**Comment by Lord-Haji** [comment]
As I am seeing multiple wild card images in <a href="http://imgur.com/a/68zvq">Here</a>

Not sure which one to add

**Comment by Lord-Haji** [comment]
Still in debug state, but open for reviews

**Comment by ghost** [comment]
> As I am seeing multiple wild card images in Here
>Not sure which one to add

There is a wild draw 4 and a regular wild. Maybe that's why you are seeing duplicates

**Comment by HoeenCoder** [comment]
The images didnt get applied when i ran the `yellow +2` test, make sure they work here.

Also, @AshleyPikachu there are 4 wild cards, whats the idea behind that?

**Comment by ghost** [comment]
4 wild cards? Dang, I thought there were less

<s>Try hard</s>

Just pick one i guess?

**Comment by HoeenCoder** [comment]
TODO:

(moved to OP)

New images origin http://imgur.com/gallery/YKb8m

**Comment by AshleyPikachu** [comment]
Hi, sorry I was at school. I'll talk to you live about this on Discord or SG, I though there were 4 wilds for some reason, I'll make a mew one after we talk,

**Comment by Lord-Haji** [comment]
Adding ``if (typeof img === 'object') img = img[Math.floor(Math.random() * img.length)];`` doesn't display any image 
scrnsht

Because variable ``img`` is always an object

**Comment by Lord-Haji** [comment]
Also the 0 cards were left out @AshleyPikachu u need to add them

**Comment by HoeenCoder** [comment]
ok yeah we need to edit the wild ones into 1 type of card, mb on the `typeof object` thing

**Comment by HoeenCoder** [comment]
Also, for credits I meant @AshleyPikachu told me that we needed to credit someone for some of the images used.

**Comment by ghost** [comment]
Wasn't the card images from pokemon TGC 2 for the game boy?

**Comment by ghost** [comment]
We can put the credits inside the uno showcase OR in the source code or in UNO help

**Comment by Lord-Haji** [comment]
@sparkychildcharlie are you okay with the credits ?

**Comment by HoeenCoder** [comment]
0s and Wild in https://imgur.com/a/kY1jZ

**Pull request merged**
