### PR TITLE
Update help to show /sa not /survey answer

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by DeathlyPlays** [comment]
Better version of /sa, just for aesthetic purposes/convenience.

**Comment by ghost** [comment]
Keep both imo

**Comment by ghost** [comment]
People can use either for purposes

**Comment by ghost** [comment]
I just made it for short and purposes

**Comment by DeathlyPlays** [comment]
Ah idk tbh

**Comment by DeathlyPlays** [comment]
I just got bored and decided to edit this lol

**Comment by ghost** [comment]
Just close it for now, ill edit it so help get both survey answer and /sa

**Comment by DeathlyPlays** [comment]
tbh its unnecessary

**Pull request closed without merging**
