### PR TITLE
SSB: Remove VXN

### PR DESCRIPTION
**Pull request by ghost**
Seeing as everyone want me gone, I removed all global auth. So I shall remove my Ssb mon from my server and leave from exiled and spacialgaze like the stupid coward I am.

### CODE REVIEW

**Review by DeathlyPlays — COMMENTED** [review]
How about NO (your ability) you aren't leaving Obama

**Comment by ghost** [comment]
@DeathlyPlays I'm no longer global auth, I shouldn't be even in Sgssb

**Comment by DeathlyPlays** [comment]
@vxxn As far as I know retired staff get to keep their staffmon according to @HoeenCoder. But I will leave this up to him.

**Comment by HoeenCoder** [comment]
"Since everyone wants me gone" since when?

**Comment by DeathlyPlays** [comment]
Mystifi  used eval to spam SG with "Hoeenhero sucks" and crashed SG for 6 hours, so do you really think we want you gone dude?

**Comment by HoeenCoder** [comment]
Ive managed to duplicate every user on the server x30...

Userlist was a mess and i had to restart to fix it. Were people happy with me? no. Did they get over it because it was just a mistake? yes. And I didn't let it make me quit SG either, your going to make mistakes, I make them all the time. On SG and main, even Zarel screws up, sometimes really bad.

**Comment by DeathlyPlays** [comment]
Cough cough fs refractor cough cough

**Comment by Mystifi** [comment]
> Mystifi used eval to spam SG with "Hoeenhero sucks" and crashed SG for 6 hours, so do you really think we want you gone dude?

That's true, I forgot to set an interval for `setInterval`, so we were stuck in an infinite loop. Breaking stuff is part of the coding process, and it's part of learning as well. Toying around with /eval isn't the best thing to do, but as long as you don't abuse it too much/break any rules or the server too much, you'll be fine - especially if you apologize after doing so and learn from your mistakes.

> Seeing as everyone want me gone, I removed all global auth. So I shall remove my Ssb mon from my server and leave from exiled and spacialgaze like the stupid coward I am.

As far as I know, no one wants you gone. You're a good person who has contributed to so many communities in both the chat and to the server, and that takes a lot of brain power. I understand that depression makes everything seem so one-sided; it's literally tunnel-vision. Don't get too sucked into it. If you ever need to talk to me about stuff like this, @vxxn, feel free. I've helped Hiro a couple of times, and I help people every day in The Happy Place on main.

I can't pretend to understand your situation because I've been heavily inactive as of late due to personal reasons. However, don't beat up yourself for something that isn't going to matter in a month or so.

**Comment by DeathlyPlays** [comment]
I broke Exiled for a whole day just failing my fs refractor @vxxn THEN upon that I ddosed Exiled on accident xD you good fam

**Pull request closed without merging**
