### PR TITLE
Add special custom move

### PR DESCRIPTION
**Pull request by ghost**
Team player ~~~~~> Toxic endeavors

### CODE REVIEW

**Comment by ghost** [comment]
Actually done now

**Comment by ghost** [comment]
Toxic endeavors: endeavor, but has a 33% chance to badly poison the foe

**Comment by HoeenCoder** [comment]
Will merge post afd

**Comment by ghost** [comment]
K

**Comment by HoeenCoder** [comment]
Read my above comment, i need to edit your setup on SG which can cause crashes if you new move dosent exist yet.

**Comment by ghost** [comment]
Ok

**Pull request merged**
