### PR TITLE
Formats: Update Random Metronome Battle

### PR DESCRIPTION
**Pull request by ghost**
This allows metronome battles to be affected by PotD and removes team preview, adding more randomness.

### CODE REVIEW

**Review by DeathlyPlays — COMMENTED** [review]
For consistency I'd do the same for regular Metronome Battles

**Comment by HoeenCoder** [comment]
We should stop inheriting other formats rulesets all together

**Comment by ghost** [comment]
@HoeenCoder certain things should (eg teambuilder teams) but others shouldnt unless necessary (random formats)

**Comment by DeathlyPlays** [comment]
I prefer not inheriting any formats personally in my metas

**Comment by ghost** [comment]
closing cus WL

**Pull request closed without merging**
