### PR TITLE
Moves -Stellation

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
dark claw needs its space

**Comment by DeathlyPlays** [comment]
"darkclaw": {
		id: "darkclaw",
		name: "darkclaw",
		basePower: 143,
		accuracy: 100,
		category: "Physical",
		pp: 0.625,
		flags: {protect: 1, distance: 1},
		secondary: false,
		onModifyMove: function (move, pokemon, target) {
			move.type = '???';
			this.add('-activate', pokemon, 'move: Dark Claw');
		},
		onHit: function (target, source) {
			this.attrLastMove('[still]');
			this.add('-anim', source, "Hone Claws", source);
			this.add('-anim', source, "Shadow Claw", source);
		},
		priority: 0,
		target: "any",
		type: "Filth",
	},

**Comment by DeathlyPlays** [comment]
It does exist

**Comment by ghost** [comment]
"darkclaw": {
id: "darkclaw",
name: "Dark Claw",
basePower: 143,
accuracy: 100,
category: "Physical",
pp: 0.625,
flags: {protect: 1, distance: 1},
secondary: false,
onModifyMove: function (move, pokemon, target) {
move.type = '???';
this.add('-activate', pokemon, 'move: Dark Claw');
},
onHit: function (target, source) {
this.attrLastMove('[still]');
this.add('-anim', source, "Hone Claws", source);
this.add('-anim', source, "Shadow Claw", source);
},
priority: 0,
target: "any",
type: "Filth",
},

**Comment by ghost** [comment]
If anyone can add that without making a new pr, it'll be highly appreciated

**Comment by ghost** [comment]
Edit done

**Comment by ghost** [comment]
Ready to merge @HoeenCoder

**Pull request merged**
