### PR TITLE
SSBFFA: Ban Certain Abilities + Cleanup typos

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Grats it works! Although there are more abilities you need to ban...

**Comment by DeathlyPlays** [comment]
Which @Lycanium-Z

**Comment by ghost** [comment]
Oh, just Moody

**Comment by ghost** [comment]
its quite simple since moody is a hidden ability

**Comment by ghost** [comment]
I guess thats it. Unless you wanna remove the allowed uber mons @DeathlyPlays

**Comment by DeathlyPlays** [comment]
Nah we good

**Pull request merged**
