### PR TITLE
Travis resolutions

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by Lord-Haji** [comment]
ohh lel

**Comment by HoeenCoder** [comment]
I ran my test by replacing ours with boilerplates, that passed. IDK if we should use boilerplates avatar code or not though. id like to pinpoint the actuall error

**Comment by HoeenCoder** [comment]
Ill probably use Phils setup for CAs, but I want to ask permission first.

**Comment by Mystifi** [comment]
There are several things with the customavatar file from spacing alone that can be fixed. I will try submitting a fix later today.

**Comment by HoeenCoder** [comment]
@Mystifi its not spacing it cant find `config/avatars` for some reason

All eslint issues are resolved

**Comment by HoeenCoder** [comment]
Uh well this is a nice surprise, i expected it to fail again.

**Comment by HoeenCoder** [comment]
@Mystifi do you think you and me can look into the issues with our current avatar setup and the geoip-ultralight issue?

**Comment by Lord-Haji** [comment]
Now this should work fine @HoeenCoder

**Comment by HoeenCoder** [comment]
@Lord-Haji I had it working 30 minutes ago 
https://travis-ci.org/HoeenCoder/SpacialGaze/builds/185213640

**Comment by HoeenCoder** [comment]
It needs to pass the travis build

**Comment by HoeenCoder** [comment]
Looks good, just waiting on creature phil to respond to me on azure.

**Comment by Lord-Haji** [comment]
Refer to #30 for further improvements.

**Comment by HoeenCoder** [comment]
@CreaturePhil I wanted to ask if we can use your `chat-plugins/customavatar.js` code from Showdown-Boilerplate, were having some travis issues with ours and yours works better.

**Comment by CreaturePhil** [comment]
yeah you can

**Comment by HoeenCoder** [comment]
Thanks phil, I appreciate it.

**Comment by HoeenCoder** [comment]
@Mystifi check your edits, i'm not sure they are working properly, or if its just the unregistered server cant show avatars thing. 

- One of the reasons is its trying to set the avatar link to `http://http//i.imgur.com/tfYS6TN.png` (when using `http//i.imgur.com/tfYS6TN.png`) The avatar should show up in the `` because that's not what the client restricts concerning avatars.

- It crashes if it dosen't start with a http:// it should just fail instead.

- When i tested phil's copy the avatars showed up in `config/avatars/` they aren't now.

**Comment by HoeenCoder** [comment]
@Lord-Haji 

`Lord-Haji  wants to merge 20 commits into HoeenCoder:sqlite3-depreciated from unknown repository`

What did you do?!?

**Comment by Mystifi** [comment]
Alright, the crashes were because I missed an `!` operator.

**Comment by Lord-Haji** [comment]
I did absolutely nothing ... ! @HoeenCoder

**Pull request closed without merging**
