### PR TITLE
Add Metronome Battle format

### PR DESCRIPTION
**Pull request by Spandamn**

### CODE REVIEW

**Comment by HoeenCoder** [comment]
@Spandamn After testing: Sets are getting rejected because the pokemon cannot learn metronome, and are NOT getting rejected when they have a move other than metronome.

**Comment by Spandamn** [comment]
Fixed

**Comment by HoeenCoder** [comment]
Will struggle with travis & finish testing later

**Comment by Spandamn** [comment]
Okay

**Pull request merged**
