### PR TITLE
SGSSB: Nerf VXN

### PR DESCRIPTION
**Pull request by ghost**
I have no idea on how I made a useless mon so OP...

### CODE REVIEW

**Comment by HoeenCoder** [comment]
Hey can you remove some of the animations on your C move? Theres way too many.

**Comment by ghost** [comment]
<s>Aww</s> ok

**Comment by ghost** [comment]
Tell me if you want me to remove more

**Comment by HoeenCoder** [comment]
Limit it to 5 please

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
@HoeenCoder ready to merge

**Pull request merged**
