### PR TITLE
Badges: Improvements

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by Lord-Haji** [comment]
badgelist
This somewhat looks like this....

**Comment by Lord-Haji** [comment]
BadgesProfile
Badges in profile looks kinda like this...

**Comment by Lord-Haji** [comment]
The travis fail at economy.js is already fixed in #29

**Comment by HoeenCoder** [comment]
We can merge this after 29 is merged, and once this is tested, approved ect

**Comment by HoeenCoder** [comment]
2 concerns though.

- 1 The travis failures here are from your edits as well as not having 29 merged.
- 2  Could you setup a proper help reply for the badges commands?

**Comment by Mystifi** [comment]
There's a lot of redundant code in here that should be cleaned up, too, such as `toId(userid)` being called when `userid` is already an ID.

**Comment by Lord-Haji** [comment]
@HoeenCoder I want to inform u one thing...
the one travis fail is fixed in PR #29 if it gets merged first
npm test will pass

**Comment by HoeenCoder** [comment]
No, these issues (minus the economy one) are from this PR http://pastebin.com/BLtaVqrz

**Pull request closed without merging**
