### PR TITLE
Dubtrack: Command Found on OCPU

### PR DESCRIPTION
**Pull request by DeathlyPlays**
Cool dubtrack feature that will not only link to the dubtrack, but also say what's playing when someone uses /dubtrack.

### CODE REVIEW

**Comment by Lord-Haji** [comment]
PR naming not at all up to the work

**Comment by Mystifi** [comment]
Isn't this from panpawn's Gold server? I like cool plugins, but this seems very nearly (if not completely) copied...

**Comment by DeathlyPlays** [comment]
@Mystifi I found it on OCPU

**Comment by HoeenCoder** [comment]
Why did this get closed?

**Comment by DeathlyPlays** [comment]
Not my code, appears to be a huge issue @HoeenCoder

**Comment by DeathlyPlays** [comment]
I never claimed it as my own tbf

**Comment by HoeenCoder** [comment]
Just make sure to credit the creator, Im mostly concerned about new developers who are trying to claim others work as thier own.

**Comment by DeathlyPlays** [comment]
Mmm mk

**Comment by Mystifi** [comment]
I never said it was a huge issue? :|

**Comment by DeathlyPlays** [comment]
LOL

**Pull request merged**
