### PR TITLE
panpawn made this news system, not u Lord Haji

### PR DESCRIPTION
**Pull request by KewlStatics**
Ty for Introducing the feature,But shldnt we forgot panpawn for the code!

### CODE REVIEW

**Comment by Lord-Haji** [comment]
Use correct English
And this is my code . Compare the diff properly

**Comment by HoeenCoder** [comment]
While it does bear some similarities to golds news system, its very different in many ways.

**Comment by DarkNightSkies** [comment]
Um...you should give proper credits

**Comment by HoeenCoder** [comment]
I don't feel there are enough simalaraties, if @Lord-Haji says its copied from gold and modified ill add credits to panpawn, otherwise its fine as is.

**Comment by Lord-Haji** [comment]
@DarkNightSkies always say something before checking it properly

**Pull request closed without merging**
