### PR TITLE
UNO: Prevent +2, Skip, and Reverse cards being the first card in the pile

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by DeathlyPlays** [comment]
Not that this isn't a good idea, but I feel it would be more appropriate if it were added to main https://github.com/Zarel/Pokemon-Showdown.  Seeing as this would be an update rather on their side.

**Comment by HoeenCoder** [comment]
Check the PR on main for my thoughts.

**Comment by HoeenCoder** [comment]
Also, it would probably of been best to let @Gligar open the PR since he wrote the code.

**Comment by DeathlyPlays** [comment]
He told me to do it

**Comment by HoeenCoder** [comment]
ok nvm the second comment then

**Pull request closed without merging**
