### PR TITLE
Allow voices to start and create tours

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by Lord-Haji** [comment]
Policy approval required

**Comment by ghost** [comment]
What @Lord-Haji Said. Also, I doubt voices need to create tours with the current auth as of now. Maybe if we get some more active people to be global voices <del>Like me</del> It could work better. Maybe instead Charon should make tours available for voices? That works about the same as what Insist is trying to achieve.

**Comment by Mystifi** [comment]
I don't think Voices should be able to create tours; you can leave that to a room bot. As far as Charon Bot, you're going to want to talk to The Run about that.

**Comment by HoeenCoder** [comment]
Closing because we would rather leave voices as a rank that marks them as "good users" if you mean allow G voices to start lobby tours, i can get charon bot setup to handle that really easy.

**Pull request closed without merging**
