### PR TITLE
SSB: add dialougue to link to players guide

### PR DESCRIPTION
**Pull request by ghost**
When one is actually made, link me to it so i can update the PR> yes I know that there is a url where the actual link instead of where the future players guide will be

### CODE REVIEW

**Comment by HoeenCoder** [comment]
Why not add a README.md in the `mods/sgssb/` folder? the README can contain the info.

**Comment by ghost** [comment]
Good idea

**Comment by ghost** [comment]
#187 merge that for guide

**Comment by Stellation** [comment]
Test

**Comment by ghost** [comment]
added 2 readmes for rssb and ssbffa]

**Comment by ghost** [comment]
I'm abandoning this ship for now @AshleyPikachu can you make a guide for all 3 ssb games for sg?

**Pull request closed without merging**
