### PR TITLE
Move custom plugins to spacialgaze-plugins folder

### PR DESCRIPTION
**Pull request by Lord-Haji**
I had these changes on #30 . But i forgot to RePR it to #31 sorry... 👍

### CODE REVIEW

**Comment by HoeenCoder** [comment]
Btw, if your changes aren't similar to each other (aka the badges edits & the movement of files) you can make separate PRs.

**Comment by HoeenCoder** [comment]
@Mystifi what do you think of these changes? Ill test them soon-ish.

**Comment by Mystifi** [comment]
Why do we need them moved to a separate plugin? It makes more hassle since other servers pull from this that aren't going to be named "SpacialGaze."

**Comment by Mystifi** [comment]
This kinda just seems like a "let's make this server as unique as possible" thing, and in this case, it wouldn't be, since Gold has it added. :|

**Comment by Lord-Haji** [comment]
Idk what gold has done 
@Mystifi
But as i was a EOS Dev i PRd this coz EOS had separate files for them
Also it will minimize the chances of conflicts
And also good for proper code alignment 
We could also mention them in the README.MD to not touch the chat-plugins folder at all

**Comment by Mystifi** [comment]
HoeenHero and I were thinking of simply combining many of the chat-plugins/ files since many of them are similar. For instance:

`chat-plugins/uno.js` + `chat-plugins/dice.js` => `chat-plugins/games.js`

All extra games would go into `chat-plugins/games.js`. As for any clutter in there, we could work on refactors...but it would reduce a lot of the clutter anyways without having to make a separate folder just for our own plugins.

**Comment by Lord-Haji** [comment]
We could just do ``spacialgaze-plugins/games.js``

**Comment by HoeenCoder** [comment]
Badge issue: 
badges issue

Handled right before I commented

**Pull request merged**
