### PR TITLE
Remove request

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by HoeenCoder** [comment]
This wont work on windows since `wget` isn't a command there.

**Comment by HoeenCoder** [comment]
Um if you squash merged when you updated with HoeenCoder:master, that can cause you to take credit for others work..

**Comment by Lord-Haji** [comment]
ok Ill rePR @HoeenCoder I was unaware of that fact

**Comment by HoeenCoder** [comment]
ok

**Pull request closed without merging**
