### PR TITLE
Digimon Balancing (Kraken Mare)

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by DeathlyPlays** [comment]
Do Not Merge until I fix it up

**Comment by DeathlyPlays** [comment]
Uhhh this is really messy o3o

**Comment by RagiingAlways** [comment]
I told you it wasn't ready. We are mid- 2.0v update. Thats why I told you you shouldn't

**Comment by RagiingAlways** [comment]
You said you were just grabbing moves.

**Comment by DeathlyPlays** [comment]
Mmm ok

**Pull request closed without merging**
