### PR TITLE
Profile: Major Additions

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by HoeenCoder** [comment]
Ok as i'm testing this heres what i've found that needs to be fixed:

- Every user appears to have DEV status

- Friend code appears to be indented in too far, which also effects anything after that (pokemon go team) Indentation Error

- You need to add help documentation if your going to use `this.parse('/help command');` (help documentation is perferable)

- We should have a command (such as `/profilehelp` or just add `/help profile`) that gives a list of every usable command for `/profile`

- I think we should allow setting background image *or* color.

- `/setace` should verify that the pokemon selected exists.

- `/deleteace` shouldn't say `(users)'s background was deleted.` when it works lol

- Don't use `/team` as a command, I want to use that later for a major project.

**Comment by Lord-Haji** [comment]
@HoeenCoder Visual glitches were fixed
xx
locally

**Comment by HoeenCoder** [comment]
Then push your changes to github so I can test them.

**Comment by Lord-Haji** [comment]
Profile: Bug fixes tracking:
1. [x] Every user appears to have DEV status
2. [x] Friend code appears to be indented in too far, which also effects anything after that (pokemon go team)
3. [ ] You need to add help documentation if your going to use this.parse('/help command'); (help documentation is perferable)
4. [ ] We should have a command (such as /profilehelp or just add /help profile) that gives a list of every usable command for /profile
5. [ ] /setace should verify that the pokemon selected exists.
6. [x] /deleteace shouldn't say (users)'s background was deleted. when it works lol
7. [x] Don't use /team as a command, I want to use that later for a major project.
8. [ ] Clean Ups(Final)

**Comment by Lord-Haji** [comment]
Fixed dev bug
not expected from u @Mystifi

**Comment by Mystifi** [comment]
My bad, I accidentally erased it when I was moving from `user` to `userid`. I don't think saying "I don't expect that from you..." is necessary, though.

**Comment by HoeenCoder** [comment]
@Mystifi can you PM me on SG?

**Pull request closed without merging**
