### PR TITLE
Add evDrops and totalEvDrops to raw data

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by Lord-Haji** [comment]
Missing raticatealola

**Comment by Lord-Haji** [comment]
By Looking at the data i think megas have same evDrops as normals
Can we not use only them for saving space ?

**Comment by HoeenCoder** [comment]
- There are missing alola fomes, I was going to add them manually after the JSON was cleaned

- Megas need thier ev drops listed in the JSON for the EXP system to work correctly

- I asked you to clean the JSON not steal the credit for writing it.

**Comment by Lord-Haji** [comment]
Ohh I didn't understand and I don't want credits

**Comment by HoeenCoder** [comment]
np

**Pull request closed without merging**
