### PR TITLE
Formats: Add Gen 2 Doubles

### PR DESCRIPTION
**Pull request by ghost**
Contemplating if this should exist... Requires further discussion (unless someone wants to add it because why not).

### CODE REVIEW

**Comment by DeathlyPlays** [comment]
I honestly feel this is more of a thing on main seeing as our community isn't this large nor requested it

**Comment by ghost** [comment]
yeah, but for now leave this open so people can input their opinion

**Comment by ghost** [comment]
I have to agree with insist on this one

**Comment by HoeenCoder** [comment]
Doubles did not exist in gen 2

**Comment by DeathlyPlays** [comment]
Thought so @HoeenCoder

**Pull request closed without merging**
