### PR TITLE
Add Kanto Region Evolution Data

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by HoeenCoder** [comment]
#74

**Comment by Lord-Haji** [comment]
@HoeenCoder I doubt about Chansey and Hitmonlee/chan/top how will we trigger them when writing the script

**Comment by Lord-Haji** [comment]
I think Chansey should be 
 Chansey: oval stone held + high friendship + level Mark: trigger: 'item', type: 'friendship', exact: 'ovalstone'

**Comment by Lord-Haji** [comment]
I wont fix Hitmon group Ill get @Hirotto fix it

**Comment by Lord-Haji** [comment]
Bug Sigilyph but ill let its owner fix

**Comment by HoeenCoder** [comment]
if we did `Chansey: oval stone held + high friendship + level Mark: trigger: 'item', type: 'friendship', exact: 'ovalstone'` the handler would think that you just need to use oval stone like a water stone, Happiny needs to hold it and level up, so the trigger (when we should check for evolution) needs to be `level`, it would probably work with `Chansey: trigger: 'level', type: 'friendship', exact: 'ovalstone'`

**Comment by Lord-Haji** [comment]
Okay chansey fixed @HoeenCoder But how will we trigger the hitmon family ?
shouldn't we introduce new trigger called ``stats`` type ``nul`` exact ``atk/def/spdef
``

**Comment by HoeenCoder** [comment]
No when the pokemon is ready to evolve it will check stats to determine what it is evolving into

**Pull request merged**
