### PR TITLE
Digimon

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by ghost** [comment]
Odd...

**Comment by DeathlyPlays** [comment]
how is this wrong...

**Comment by ghost** [comment]
>This branch has conflicts that must be resolved

**Comment by ghost** [comment]
>>This branch has conflicts that must be resolved

**Comment by ghost** [comment]
Mfw no meme arrow

**Comment by DeathlyPlays** [comment]
There lol

**Comment by ghost** [comment]
That's better

**Comment by DeathlyPlays** [comment]
yup

**Comment by ghost** [comment]
Yay! Too bad the Travis build failed lol

**Pull request merged**
