### PR TITLE
Digimon: Make digimon Showdown triples 6v6

### PR DESCRIPTION
**Pull request by ghost**
[The people have spoken](http://imgur.com/qvY0WZq)

### CODE REVIEW

**Comment by Lord-Haji** [comment]
Just add a new Tier for it ?

**Comment by ghost** [comment]
There's already a tier, its just an update

**Comment by DeathlyPlays** [comment]
Nah @Lord-Haji we want this one to be Triples 6v6 bc Doubles is too fast w/ the HP balancing

**Comment by DeathlyPlays** [comment]
We ran a poll and everything this is what the community wants

**Comment by HoeenCoder** [comment]
Did you test this? I think triples would make it faster, why not increase base hp? (you can still do triples).

**Comment by ghost** [comment]
Depends on what @AshleyPikachu wants. Imo let them stay the same because it'll go too fast, maybe this'll slow down the game a bit

**Pull request merged**
