### PR TITLE
Fix Ashley's Ability

### PR DESCRIPTION
**Pull request by Spandamn**
this would deny setting any terrain if ashley is active.

### CODE REVIEW

**Comment by HoeenCoder** [comment]
Other terrains (in this case via psychic surge) can be set still.

**Comment by Spandamn** [comment]
Weird

**Comment by Mystifi** [comment]
`actives.some(pokemon => {return toId(pokemon.name) === 'ashleythepikachu';})` is redundant; you can use the arrow to imply the `return` like this:

`actives.some(pokemon => toId(pokemon.name) === 'ashleythepikachu')`

**Comment by Lord-Haji** [comment]
@Spandamn Any updates yet?

**Comment by DeathlyPlays** [comment]
:p

**Comment by ghost** [comment]
This still exists....

**Comment by DeathlyPlays** [comment]
What are the effects supposed to be?

**Comment by HoeenCoder** [comment]
Electric terrain should stay on even if another terrain is trying to start (like with heavy rain/sun/wind)

**Comment by ghost** [comment]
So "primal terrain" so be persistent the terrain effects?

**Comment by HoeenCoder** [comment]
Yes

**Comment by Spandamn** [comment]
@HoeenCoder this _should_ work

**Comment by HoeenCoder** [comment]
Sorry @Spandamn but it failed testing again, grassy terrain could be set (via move not ability), didnt test ability.

**Comment by DeathlyPlays** [comment]
@Spandamn do you want me to close this or do you plan on working on it

**Comment by DeathlyPlays** [comment]
Btw Terrains can exist even with Heavy Rain/Rain etc

**Comment by HoeenCoder** [comment]
Closing, we want this but its dead.

**Pull request closed without merging**
