### PR TITLE
attempt to fix botanical Gardens

### PR DESCRIPTION
**Pull request by ghost**
Havent tested it yet cus im on a train as of this message

### CODE REVIEW

**Comment by HoeenCoder** [comment]
Shouldn't of merged if it was untested...

**Comment by DeathlyPlays** [comment]
Well it was just an arg change that might be more fitting and work?

**Comment by HoeenCoder** [comment]
Why not test and make sure it works before merging?

Its really not that hard.

**Comment by DeathlyPlays** [comment]
I'll test it rn

**Pull request merged**
