### PR TITLE
Refactor titles to use 1 Db json

### PR DESCRIPTION
**Pull request by Lord-Haji**
Found in suggestions list.
@HoeenCoder I think we don't need the ``titleCheck`` function we could easily do with a single function should i do that ?

### CODE REVIEW

**Comment by Mystifi** [comment]
I need to refactor all of this anyways, but yes, it could be added to one database.

**Comment by Lord-Haji** [comment]
Did u check this @Mystifi 
It's tested with @HoeenCoder in my test server

**Comment by Lord-Haji** [comment]
@Mystifi r u ready yet?

**Comment by HoeenCoder** [comment]
@Lord-Haji be sure to test your changes, run all the commands associated ect, to make sure it works.

**Pull request merged**
