### PR TITLE
Cleaning up

### PR DESCRIPTION
**Pull request by RagiingAlways**

### CODE REVIEW

**Comment by Mystifi** [comment]
Um...

**Comment by HoeenCoder** [comment]
This is getting squashed dw.

Were working on getting the build to pass.

**Comment by HoeenCoder** [comment]
Apprently i didnt notice that travis is for the first 100 builds only....

So ill be dropping it after this. I guess we could merge this as is (eslint is happy now)

Probably merge into a alternate branch though and test using that

**Comment by HoeenCoder** [comment]
@RagiingAlways can you reopen this PR but instead of merging into `master`, merge into `cleanup`

**Pull request closed without merging**
