### PR TITLE
Create items.js for ssbffa

### PR DESCRIPTION
**Pull request by ghost**
Will add my item

### CODE REVIEW

**Comment by ghost** [comment]
Ill eventually fix Travis after the seasonal

**Review by HoeenCoder — COMMENTED** [review]
`isNonStandard: true,`

**Comment by ghost** [comment]
Lol sry, fixed

**Comment by ghost** [comment]
Oh, I found this really awesome js formater that almost Travis builds code, I really recommend it!

http://jsbeautifier.org

**Comment by HoeenCoder** [comment]
mb

**Comment by DeathlyPlays** [comment]
I used to use JS Beautify it helps find errors but eh else lines get screwed with it

**Comment by DeathlyPlays** [comment]
But it does annihilate trailing spaces.... indentions etc

**Comment by ghost** [comment]
Yeah

**Pull request merged**
