### PR TITLE
Fix icons

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by HoeenCoder** [comment]
You only changed the size for party slots, change it for the box slots too.

Also i need to run some tests to make sure theres no unintended consequences, if not then this is good to go.

**Comment by Lord-Haji** [comment]
The Display is although a bit awkward But it fixes the issue.

**Comment by Lord-Haji** [comment]
@HoeenCoder We Might ask ppl not to use Full screen while Playing SGgame

**Comment by Lord-Haji** [comment]
@HoeenCoder This looks kinda like 
img

**Comment by HoeenCoder** [comment]
ATM this is better than before, it prevents any issues with multiple pokemon showing.

**Pull request merged**
